const STUDENTS=[["Budi Santoso","260101"],["Satria budi Kusuma","260102"],["M.fazriel r","260103"],["Luthfi al Fattah","260104"],["Citra lestari","260105"],["Kania Aprilia","260106"],["Dewiya Rosawati","260107"],["Kratos ","260108"],["Albert","260109"],["Michelle","260110"],["Yoga Pranata","260111"],["Rani Maharani","260112"],["Bagas Dribbel","260113"],["Lisa black pink","260114"],["bie ellies","260115"],["cristopher nolan","260116"],["Ronaldo","260117"],["Messi","260118"],["hayato","260119"],["william","260120"],["baehliel","260121"],["Kitty","260122"]];function users(){let u=JSON.parse(localStorage.users||"[]");if(!u.some(x=>x.email==="admin@absensi.com")){u.push({name:"Admin",email:"admin@absensi.com",password:"admin123"});localStorage.users=JSON.stringify(u)}return u}function requireLogin(){if(!localStorage.session)location="login.html"}function logout(){localStorage.removeItem("session");location="login.html"}function initLogin(){
  if(localStorage.session){location="index.html";return}
  loginForm.onsubmit=e=>{
    e.preventDefault();
    const em=email.value.trim().toLowerCase(), pw=password.value;
    const u=users().find(x=>x.email===em && x.password===pw);
    if(!u){msg.textContent="Email atau password salah.";msg.className="error";return}
    localStorage.session=JSON.stringify(u);
    location="index.html";
  };
  document.getElementById("toggleLoginPassword").onclick=()=>{
    password.type=password.type==="password"?"text":"password";
    toggleLoginPassword.textContent=password.type==="password"?"◉":"◉";
  };
}
function initSignup(){
  signupForm.onsubmit=e=>{
    e.preventDefault();
    const n=name.value.trim(), em=email.value.trim().toLowerCase(), pw=password.value, cp=confirm.value;
    if(!n||!em||!pw||!cp){msg.textContent="Semua kolom wajib diisi.";msg.className="error";return}
    if(pw.length<6){msg.textContent="Password minimal 6 karakter.";msg.className="error";return}
    if(pw!==cp){msg.textContent="Konfirmasi password tidak sama.";msg.className="error";return}
    let u=users();
    if(u.some(x=>x.email===em)){msg.textContent="Email sudah terdaftar. Gunakan email lain.";msg.className="error";return}
    const akun={name:n,email:em,password:pw};
    u.push(akun);localStorage.users=JSON.stringify(u);
    localStorage.session=JSON.stringify(akun);
    msg.textContent="Akun berhasil dibuat. Mengalihkan...";
    msg.className="success";
    setTimeout(()=>location="index.html",500);
  };
  document.getElementById("togglePassword").onclick=()=>{
    password.type=password.type==="password"?"text":"password";
  };
  document.getElementById("toggleConfirm").onclick=()=>{
    confirm.type=confirm.type==="password"?"text":"password";
  };
}
function day(){return new Date().toISOString().slice(0,10)}function data(){return JSON.parse(localStorage.attendance||"{}")}function count(r){let c={Hadir:0,Izin:0,Sakit:0,Alfa:0};Object.values(r).forEach(x=>c[x]++);return c}function initials(n){return n.split(" ").map(x=>x[0]).slice(0,2).join("")}
function initDashboard(){let s=JSON.parse(localStorage.session),p=JSON.parse(localStorage.school||'{"school":"SMK Mutiara Harapan","className":"XI RPL 3 · Rekayasa Perangkat Lunak","image":""}'),r=data()[day()]||{},c=count(r);userName.textContent=s.name;userAvatar.textContent=initials(s.name);schoolName.textContent=p.school;className.textContent=p.className;if(p.image)schoolPhoto.innerHTML='<img src="'+p.image+'">';total.textContent=STUDENTS.length;hadir.textContent=c.Hadir;izin.textContent=c.Izin;sakit.textContent=c.Sakit;alfa.textContent=c.Alfa;tidak.textContent=c.Izin+c.Sakit+c.Alfa;let pc=(c.Hadir/STUDENTS.length*100).toFixed(1);pct.textContent=pc+"%";hadirPct.textContent=pc+"% dari siswa";let ss=["Matematika · 07:00 - 08:30 · XI RPL 3","Bahasa Indonesia · 09:00 - 10:30 · XI RPL 3","Mapel pilihan · 11:00 - 12:30 · XI RPL 3"," Kreatif inovatif & kewirausahaan· 13:00 - 14:30 · XI RPL 3"];schedule.innerHTML=ss.map(x=>'<div class="student"><span>▣</span><div><strong>'+x+'</strong><br><small>Jadwal hari ini</small></div><a class="primary" href="absensi.html">Absen →</a></div>').join("");activity.innerHTML='<p>✓ '+c.Hadir+' siswa hadir hari ini.</p><p>▦ Rekap tersedia untuk dilihat dan diekspor.</p><p>♧ '+STUDENTS.length+' siswa terdaftar.</p>'}
function editSchool(){let p=JSON.parse(localStorage.school||'{"school":"SMK Mutiara Harapan","className":"XI RPL 3 · Rekayasa Perangkat Lunak","image":""}');editSchoolName.value=p.school;editClassName.value=p.className;preview.src=p.image||"";preview.style.display=p.image?"block":"none";modal.classList.add("show");editImage.onchange=()=>{let f=editImage.files[0];if(f){let r=new FileReader();r.onload=()=>{preview.src=r.result;preview.style.display="block"};r.readAsDataURL(f)}}}function closeModal(){modal.classList.remove("show")}function saveSchool(){let p={school:editSchoolName.value,className:editClassName.value,image:preview.src.startsWith("data:")?preview.src:(JSON.parse(localStorage.school||"{}").image||"")};localStorage.school=JSON.stringify(p);closeModal();initDashboard()}
let att={};function initAttendance(){date.textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});att=data()[day()]||{};totalS.textContent=STUDENTS.length;search.oninput=renderStudents;renderStudents();updateAtt()}function renderStudents(){let q=(search.value||"").toLowerCase();students.innerHTML=STUDENTS.map((s,i)=>({s,i})).filter(x=>x.s[0].toLowerCase().includes(q)||x.s[1].includes(q)).map(x=>{let st=att[x.i]||"";return '<div class="student"><span>'+String(x.i+1).padStart(2,"0")+'</span><div class="face">'+initials(x.s[0])+'</div><div><strong>'+x.s[0]+'</strong><br><small>NIS '+x.s[1]+'</small></div>'+["Hadir","Izin","Sakit","Alfa"].map(v=>'<button class="status '+v.toLowerCase()+' '+(st===v?"sel":"")+'" onclick="setAtt('+x.i+',\''+v+'\')">'+v+'</button>').join("")+'</div>'}).join("")}function setAtt(i,v){att[i]=v;renderStudents();updateAtt()}function updateAtt(){let c=count(att),m=Object.keys(att).length;marked.textContent=m;left.textContent=STUDENTS.length-m;bar.style.width=m/STUDENTS.length*100+"%";ch.textContent=c.Hadir;ci.textContent=c.Izin;cs.textContent=c.Sakit;ca.textContent=c.Alfa}function saveAttendance(){let d=data();d[day()]=att;localStorage.attendance=JSON.stringify(d);alert("Absensi berhasil disimpan.")}
function initReport(){let n=new Date();for(let i=0;i<12;i++){let d=new Date(n.getFullYear(),n.getMonth()-i,1),o=document.createElement("option");o.value=d.toISOString().slice(0,7);o.textContent=d.toLocaleDateString("id-ID",{month:"long",year:"numeric"});month.appendChild(o)}renderReport()}function monthRows(){let rows=STUDENTS.map(s=>({name:s[0],nis:s[1],Hadir:0,Izin:0,Sakit:0,Alfa:0})),m=month.value;Object.entries(data()).forEach(([d,r])=>{if(d.startsWith(m))Object.entries(r).forEach(([i,v])=>rows[i]&&rows[i][v]++)});rows.forEach(r=>{r.total=r.Hadir+r.Izin+r.Sakit+r.Alfa;r.p=r.total?Math.round(r.Hadir/r.total*100):0});return rows}function renderReport(){let rows=monthRows(),sort=[...rows].sort((a,b)=>b.p-a.p),w=[...rows].sort((a,b)=>a.p-b.p)[0],avg=rows.reduce((a,b)=>a+b.p,0)/rows.length;meetings.textContent=Object.keys(data()).filter(d=>d.startsWith(month.value)).length;avgEl=document.getElementById("avg");avgEl.textContent=avg.toFixed(1)+"%";best.textContent=sort[0].name;bd.textContent=sort[0].p+"% kehadiran";worst.textContent=w.name;wd.textContent=(w.total-w.Hadir)+" kali tidak hadir";report.innerHTML=sort.map((r,i)=>'<tr><td>'+ (i+1)+'</td><td>'+r.name+'</td><td>'+r.nis+'</td><td>'+r.Hadir+'</td><td>'+r.Izin+'</td><td>'+r.Sakit+'</td><td>'+r.Alfa+'</td><td class="'+(r.p<75?"warn":"safe")+'">'+r.p+'%</td><td class="'+(r.p<75?"warn":"safe")+'">'+(r.p<75?"Perlu Perhatian":"Aman")+'</td></tr>').join("");let ds=Object.entries(data()).filter(([d])=>d.startsWith(month.value));chart.innerHTML=ds.length?ds.map(([d,r])=>{let c=count(r),p=c.Hadir/STUDENTS.length*100;return '<div class="bar" style="height:'+Math.max(3,p)+'%" title="'+d+' '+p.toFixed(0)+'%"></div>'}).join(""):"<p>Belum ada data bulan ini.</p>"}function exportCSV(){let rs=monthRows(),x=[["No","Nama","NIS","Hadir","Izin","Sakit","Alfa","Persentase","Status"],...rs.map((r,i)=>[i+1,r.name,r.nis,r.Hadir,r.Izin,r.Sakit,r.Alfa,r.p+"%",r.p<75?"Perlu Perhatian":"Aman"])].map(r=>r.join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+x],{type:"text/csv"}));a.download="rekap-absensi.csv";a.click()}function exportWPS(){let rs=monthRows(),h="<html><meta charset='UTF-8'><body><h2>REKAP ABSENSI SISWA XI RPL 3</h2><table border='1'><tr><th>No</th><th>Nama</th><th>NIS</th><th>Hadir</th><th>Izin</th><th>Sakit</th><th>Alfa</th><th>Persentase</th><th>Status</th></tr>"+rs.map((r,i)=>"<tr><td>"+(i+1)+"</td><td>"+r.name+"</td><td>"+r.nis+"</td><td>"+r.Hadir+"</td><td>"+r.Izin+"</td><td>"+r.Sakit+"</td><td>"+r.Alfa+"</td><td>"+r.p+"%</td><td>"+(r.p<75?"Perlu Perhatian":"Aman")+"</td></tr>").join("")+"</table></body></html>",a=document.createElement("a");a.href=URL.createObjectURL(new Blob([h],{type:"application/msword"}));a.download="Rekap-Absensi-WPS.doc";a.click()}
